CREATE TABLE "financialMovement" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "installmentId" BIGINT NOT NULL,
    "type" VARCHAR(10) NOT NULL,
    "amount" NUMERIC(19,2) NOT NULL,
    "movementDate" DATE NOT NULL,
    "bankAccountId" BIGINT NOT NULL,
    "paymentMethodId" BIGINT NOT NULL,
    CONSTRAINT "pkFinancialMovement" PRIMARY KEY ("id"),
    CONSTRAINT "fkFinancialMovementInstallment"
        FOREIGN KEY ("installmentId") REFERENCES "installment" ("id"),
    CONSTRAINT "fkFinancialMovementBankAccount"
        FOREIGN KEY ("bankAccountId") REFERENCES "bankAccount" ("id"),
    CONSTRAINT "fkFinancialMovementPaymentMethod"
        FOREIGN KEY ("paymentMethodId") REFERENCES "paymentMethod" ("id"),
    CONSTRAINT "ckFinancialMovementType" CHECK ("type" IN ('PAYMENT', 'RECEIPT')),
    CONSTRAINT "ckFinancialMovementAmountPositive" CHECK ("amount" > 0)
);

CREATE INDEX "ixFinancialMovementInstallmentDate"
    ON "financialMovement" ("installmentId", "movementDate", "id");
