CREATE TABLE "financialAccountHistory" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "financialAccountId" BIGINT NOT NULL,
    "type" VARCHAR(30) NOT NULL,
    "actorId" VARCHAR(128) NULL,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "pkFinancialAccountHistory" PRIMARY KEY ("id"),
    CONSTRAINT "fkFinancialAccountHistoryFinancialAccount"
        FOREIGN KEY ("financialAccountId") REFERENCES "financialAccount" ("id"),
    CONSTRAINT "ckFinancialAccountHistoryType"
        CHECK ("type" IN ('CREATED', 'APPROVED_WITHOUT_WORKFLOW')),
    CONSTRAINT "ckFinancialAccountHistoryActor"
        CHECK (
            ("type" = 'CREATED' AND "actorId" IS NULL)
            OR ("type" = 'APPROVED_WITHOUT_WORKFLOW' AND "actorId" IS NOT NULL AND BTRIM("actorId") <> '')
        )
);

CREATE INDEX "ixFinancialAccountHistoryFinancialAccountId"
    ON "financialAccountHistory" ("financialAccountId", "id");

ALTER TABLE "approvalRequest"
    ADD COLUMN "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE "approvalDecision"
    ADD COLUMN "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE "financialMovement"
    ADD COLUMN "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now();
