CREATE TABLE "idempotencyRecord" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "companyId" BIGINT NOT NULL,
    "operation" VARCHAR(64) NOT NULL,
    "idempotencyKey" VARCHAR(128) NOT NULL,
    "fingerprint" CHAR(64) NOT NULL,
    "status" VARCHAR(16) NOT NULL,
    "resultReference" VARCHAR(255),
    "createdAt" TIMESTAMPTZ NOT NULL,
    "completedAt" TIMESTAMPTZ,
    CONSTRAINT "pkIdempotencyRecord" PRIMARY KEY ("id"),
    CONSTRAINT "ukIdempotencyRecordScope"
        UNIQUE ("companyId", "operation", "idempotencyKey"),
    CONSTRAINT "ckIdempotencyRecordCompany" CHECK ("companyId" > 0),
    CONSTRAINT "ckIdempotencyRecordFingerprint"
        CHECK ("fingerprint" ~ '^[0-9a-f]{64}$'),
    CONSTRAINT "ckIdempotencyRecordStatus"
        CHECK ("status" IN ('PROCESSING', 'COMPLETED')),
    CONSTRAINT "ckIdempotencyRecordCompletion" CHECK (
        ("status" = 'PROCESSING' AND "resultReference" IS NULL AND "completedAt" IS NULL)
        OR
        ("status" = 'COMPLETED' AND "resultReference" IS NOT NULL AND "completedAt" IS NOT NULL)
    )
);
