CREATE TABLE "company" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(200) NOT NULL,
    CONSTRAINT "pkCompany" PRIMARY KEY ("id"),
    CONSTRAINT "ckCompanyNameNotBlank" CHECK (BTRIM("name") <> '')
);

CREATE TABLE "branch" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "companyId" BIGINT NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    CONSTRAINT "pkBranch" PRIMARY KEY ("id"),
    CONSTRAINT "fkBranchCompany" FOREIGN KEY ("companyId") REFERENCES "company" ("id"),
    CONSTRAINT "ckBranchNameNotBlank" CHECK (BTRIM("name") <> '')
);

CREATE INDEX "ixBranchCompanyId" ON "branch" ("companyId");
