CREATE TABLE "partner" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(200) NOT NULL,
    "document" VARCHAR(14) NOT NULL,
    "customer" BOOLEAN NOT NULL,
    "supplier" BOOLEAN NOT NULL,
    "active" BOOLEAN NOT NULL,
    CONSTRAINT "pkPartner" PRIMARY KEY ("id"),
    CONSTRAINT "ukPartnerDocument" UNIQUE ("document"),
    CONSTRAINT "ckPartnerNameNotBlank" CHECK (BTRIM("name") <> ''),
    CONSTRAINT "ckPartnerDocumentFormat" CHECK ("document" ~ '^([0-9]{11}|[A-Z0-9]{12}[0-9]{2})$'),
    CONSTRAINT "ckPartnerRole" CHECK ("customer" OR "supplier")
);
