CREATE TABLE "category" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "companyId" BIGINT NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "active" BOOLEAN NOT NULL,
    CONSTRAINT "pkCategory" PRIMARY KEY ("id"),
    CONSTRAINT "fkCategoryCompany" FOREIGN KEY ("companyId") REFERENCES "company" ("id"),
    CONSTRAINT "ckCategoryNameNotBlank" CHECK (BTRIM("name") <> '')
);

CREATE INDEX "ixCategoryCompanyId" ON "category" ("companyId");

CREATE TABLE "costCenter" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "companyId" BIGINT NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "active" BOOLEAN NOT NULL,
    CONSTRAINT "pkCostCenter" PRIMARY KEY ("id"),
    CONSTRAINT "fkCostCenterCompany" FOREIGN KEY ("companyId") REFERENCES "company" ("id"),
    CONSTRAINT "ckCostCenterNameNotBlank" CHECK (BTRIM("name") <> '')
);

CREATE INDEX "ixCostCenterCompanyId" ON "costCenter" ("companyId");
