CREATE TABLE "bankAccount" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "companyId" BIGINT NOT NULL,
    "branchId" BIGINT NULL,
    "name" VARCHAR(200) NOT NULL,
    "active" BOOLEAN NOT NULL,
    CONSTRAINT "pkBankAccount" PRIMARY KEY ("id"),
    CONSTRAINT "fkBankAccountCompany" FOREIGN KEY ("companyId") REFERENCES "company" ("id"),
    CONSTRAINT "fkBankAccountBranch" FOREIGN KEY ("branchId") REFERENCES "branch" ("id"),
    CONSTRAINT "ckBankAccountNameNotBlank" CHECK (BTRIM("name") <> '')
);
CREATE INDEX "ixBankAccountCompanyId" ON "bankAccount" ("companyId");

CREATE TABLE "paymentMethod" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "companyId" BIGINT NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "active" BOOLEAN NOT NULL,
    CONSTRAINT "pkPaymentMethod" PRIMARY KEY ("id"),
    CONSTRAINT "fkPaymentMethodCompany" FOREIGN KEY ("companyId") REFERENCES "company" ("id"),
    CONSTRAINT "ckPaymentMethodNameNotBlank" CHECK (BTRIM("name") <> '')
);
CREATE INDEX "ixPaymentMethodCompanyId" ON "paymentMethod" ("companyId");
