CREATE TABLE "financialAccount" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "companyId" BIGINT NOT NULL,
    "branchId" BIGINT NOT NULL,
    "type" VARCHAR(10) NOT NULL,
    "partnerId" BIGINT NOT NULL,
    "categoryId" BIGINT NOT NULL,
    "costCenterId" BIGINT NULL,
    "issueDate" DATE NOT NULL,
    "totalAmount" NUMERIC(19,2) NOT NULL,
    "status" VARCHAR(20) NOT NULL,
    CONSTRAINT "pkFinancialAccount" PRIMARY KEY ("id"),
    CONSTRAINT "fkFinancialAccountCompany" FOREIGN KEY ("companyId") REFERENCES "company" ("id"),
    CONSTRAINT "fkFinancialAccountBranch" FOREIGN KEY ("branchId") REFERENCES "branch" ("id"),
    CONSTRAINT "fkFinancialAccountPartner" FOREIGN KEY ("partnerId") REFERENCES "partner" ("id"),
    CONSTRAINT "fkFinancialAccountCategory" FOREIGN KEY ("categoryId") REFERENCES "category" ("id"),
    CONSTRAINT "fkFinancialAccountCostCenter" FOREIGN KEY ("costCenterId") REFERENCES "costCenter" ("id"),
    CONSTRAINT "ckFinancialAccountType" CHECK ("type" IN ('PAYABLE', 'RECEIVABLE')),
    CONSTRAINT "ckFinancialAccountStatus" CHECK ("status" IN ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'SETTLED', 'CANCELLED')),
    CONSTRAINT "ckFinancialAccountTotalAmountPositive" CHECK ("totalAmount" > 0)
);

CREATE INDEX "ixFinancialAccountCompanyId" ON "financialAccount" ("companyId");

CREATE TABLE "installment" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "financialAccountId" BIGINT NOT NULL,
    "installmentNumber" INTEGER NOT NULL,
    "dueDate" DATE NOT NULL,
    "amount" NUMERIC(19,2) NOT NULL,
    CONSTRAINT "pkInstallment" PRIMARY KEY ("id"),
    CONSTRAINT "fkInstallmentFinancialAccount" FOREIGN KEY ("financialAccountId") REFERENCES "financialAccount" ("id"),
    CONSTRAINT "ukInstallmentFinancialAccountNumber" UNIQUE ("financialAccountId", "installmentNumber"),
    CONSTRAINT "ckInstallmentNumberPositive" CHECK ("installmentNumber" > 0),
    CONSTRAINT "ckInstallmentAmountPositive" CHECK ("amount" > 0)
);
