ALTER TABLE "financialAccount"
    ADD COLUMN "version" BIGINT NOT NULL DEFAULT 0;

CREATE TABLE "approvalConfiguration" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "companyId" BIGINT NOT NULL,
    "branchId" BIGINT NULL,
    "financialAccountType" VARCHAR(10) NOT NULL,
    "approvalRequired" BOOLEAN NOT NULL,
    CONSTRAINT "pkApprovalConfiguration" PRIMARY KEY ("id"),
    CONSTRAINT "fkApprovalConfigurationCompany" FOREIGN KEY ("companyId") REFERENCES "company" ("id"),
    CONSTRAINT "fkApprovalConfigurationBranch" FOREIGN KEY ("branchId") REFERENCES "branch" ("id"),
    CONSTRAINT "ckApprovalConfigurationType" CHECK ("financialAccountType" IN ('PAYABLE', 'RECEIVABLE'))
);

CREATE UNIQUE INDEX "ukApprovalConfigurationCompanyType"
    ON "approvalConfiguration" ("companyId", "financialAccountType")
    WHERE "branchId" IS NULL;

CREATE UNIQUE INDEX "ukApprovalConfigurationCompanyBranchType"
    ON "approvalConfiguration" ("companyId", "branchId", "financialAccountType")
    WHERE "branchId" IS NOT NULL;

CREATE TABLE "approvalRequest" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "financialAccountId" BIGINT NOT NULL,
    "requesterActorId" VARCHAR(128) NOT NULL,
    "status" VARCHAR(10) NOT NULL,
    CONSTRAINT "pkApprovalRequest" PRIMARY KEY ("id"),
    CONSTRAINT "fkApprovalRequestFinancialAccount" FOREIGN KEY ("financialAccountId") REFERENCES "financialAccount" ("id"),
    CONSTRAINT "ckApprovalRequestStatus" CHECK ("status" IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT "ckApprovalRequestActor" CHECK (BTRIM("requesterActorId") <> '')
);

CREATE UNIQUE INDEX "ukApprovalRequestPendingFinancialAccount"
    ON "approvalRequest" ("financialAccountId")
    WHERE "status" = 'PENDING';

CREATE TABLE "approvalDecision" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "approvalRequestId" BIGINT NOT NULL,
    "actorId" VARCHAR(128) NOT NULL,
    "decision" VARCHAR(10) NOT NULL,
    "rejectionJustification" VARCHAR(500) NULL,
    CONSTRAINT "pkApprovalDecision" PRIMARY KEY ("id"),
    CONSTRAINT "fkApprovalDecisionApprovalRequest" FOREIGN KEY ("approvalRequestId") REFERENCES "approvalRequest" ("id"),
    CONSTRAINT "ukApprovalDecisionRequest" UNIQUE ("approvalRequestId"),
    CONSTRAINT "ckApprovalDecisionType" CHECK ("decision" IN ('APPROVED', 'REJECTED')),
    CONSTRAINT "ckApprovalDecisionActor" CHECK (BTRIM("actorId") <> ''),
    CONSTRAINT "ckApprovalDecisionJustification" CHECK (
        ("decision" = 'APPROVED' AND "rejectionJustification" IS NULL)
        OR
        ("decision" = 'REJECTED' AND "rejectionJustification" IS NOT NULL AND BTRIM("rejectionJustification") <> '')
    )
);
