package com.financeiro.interfaces.rest.error;

import org.springframework.http.HttpStatus;

public enum ApiErrorType {
  PARTNER_NOT_FOUND(HttpStatus.NOT_FOUND, "PARTNER_NOT_FOUND"),
  PARTNER_DOCUMENT_ALREADY_EXISTS(HttpStatus.CONFLICT, "PARTNER_DOCUMENT_ALREADY_EXISTS"),
  INVALID_PARTNER_DOCUMENT(HttpStatus.UNPROCESSABLE_CONTENT, "INVALID_PARTNER_DOCUMENT"),
  COMPANY_NOT_FOUND(HttpStatus.NOT_FOUND, "COMPANY_NOT_FOUND"),
  BRANCH_NOT_FOUND(HttpStatus.NOT_FOUND, "BRANCH_NOT_FOUND"),
  CATEGORY_NOT_FOUND(HttpStatus.NOT_FOUND, "CATEGORY_NOT_FOUND"),
  COST_CENTER_NOT_FOUND(HttpStatus.NOT_FOUND, "COST_CENTER_NOT_FOUND"),
  BANK_ACCOUNT_NOT_FOUND(HttpStatus.NOT_FOUND, "BANK_ACCOUNT_NOT_FOUND"),
  PAYMENT_METHOD_NOT_FOUND(HttpStatus.NOT_FOUND, "PAYMENT_METHOD_NOT_FOUND"),
  FINANCIAL_ACCOUNT_NOT_FOUND(HttpStatus.NOT_FOUND, "FINANCIAL_ACCOUNT_NOT_FOUND"),
  FINANCIAL_ACCOUNT_NOT_SETTLEABLE(HttpStatus.CONFLICT, "FINANCIAL_ACCOUNT_NOT_SETTLEABLE"),
  INSTALLMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "INSTALLMENT_NOT_FOUND"),
  INSTALLMENT_ALREADY_SETTLED(HttpStatus.CONFLICT, "INSTALLMENT_ALREADY_SETTLED"),
  SETTLEMENT_AMOUNT_EXCEEDS_BALANCE(
      HttpStatus.UNPROCESSABLE_CONTENT, "SETTLEMENT_AMOUNT_EXCEEDS_BALANCE"),
  BANK_ACCOUNT_INACTIVE(HttpStatus.UNPROCESSABLE_CONTENT, "BANK_ACCOUNT_INACTIVE"),
  BANK_ACCOUNT_BRANCH_NOT_ALLOWED(
      HttpStatus.UNPROCESSABLE_CONTENT, "BANK_ACCOUNT_BRANCH_NOT_ALLOWED"),
  PAYMENT_METHOD_INACTIVE(HttpStatus.UNPROCESSABLE_CONTENT, "PAYMENT_METHOD_INACTIVE"),
  SETTLEMENT_CONFLICT(HttpStatus.CONFLICT, "SETTLEMENT_CONFLICT"),
  FINANCIAL_ACCOUNT_NOT_REVERSIBLE(HttpStatus.CONFLICT, "FINANCIAL_ACCOUNT_NOT_REVERSIBLE"),
  ORIGINAL_MOVEMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "ORIGINAL_MOVEMENT_NOT_FOUND"),
  CANNOT_REVERSE_REVERSAL(HttpStatus.UNPROCESSABLE_CONTENT, "CANNOT_REVERSE_REVERSAL"),
  ORIGINAL_MOVEMENT_ALREADY_FULLY_REVERSED(
      HttpStatus.CONFLICT, "ORIGINAL_MOVEMENT_ALREADY_FULLY_REVERSED"),
  REVERSAL_AMOUNT_EXCEEDS_BALANCE(
      HttpStatus.UNPROCESSABLE_CONTENT, "REVERSAL_AMOUNT_EXCEEDS_BALANCE"),
  PARTNER_INACTIVE(HttpStatus.UNPROCESSABLE_CONTENT, "PARTNER_INACTIVE"),
  PARTNER_ROLE_NOT_ALLOWED(HttpStatus.UNPROCESSABLE_CONTENT, "PARTNER_ROLE_NOT_ALLOWED"),
  CATEGORY_INACTIVE(HttpStatus.UNPROCESSABLE_CONTENT, "CATEGORY_INACTIVE"),
  COST_CENTER_INACTIVE(HttpStatus.UNPROCESSABLE_CONTENT, "COST_CENTER_INACTIVE"),
  IDEMPOTENCY_KEY_REQUIRED(HttpStatus.BAD_REQUEST, "IDEMPOTENCY_KEY_REQUIRED"),
  INVALID_IDEMPOTENCY_KEY(HttpStatus.BAD_REQUEST, "INVALID_IDEMPOTENCY_KEY"),
  IDEMPOTENCY_KEY_CONFLICT(HttpStatus.CONFLICT, "IDEMPOTENCY_KEY_CONFLICT"),
  IDEMPOTENCY_REQUEST_IN_PROGRESS(HttpStatus.CONFLICT, "IDEMPOTENCY_REQUEST_IN_PROGRESS"),
  RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND, "RESOURCE_NOT_FOUND"),
  CONFLICT(HttpStatus.CONFLICT, "CONFLICT"),
  SEMANTIC_VALIDATION(HttpStatus.UNPROCESSABLE_CONTENT, "VALIDATION_ERROR");

  private final HttpStatus status;
  private final String code;

  ApiErrorType(HttpStatus status, String code) {
    this.status = status;
    this.code = code;
  }

  public HttpStatus status() {
    return status;
  }

  public String code() {
    return code;
  }
}
