spring:
  application:
    name: financeiro-backend
  profiles:
    default: local
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
