spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.jdbc.autoconfigure.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.jdbc.autoconfigure.JdbcTemplateAutoConfiguration
      - org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration

logging:
  level:
    root: WARN
    com.financeiro: INFO
